# Zjazd 4 dzień 1 - źródła danych - JSON

||put|post|get|delete|
|-|-|-|-|-|
|/pet|Update an existing pet|-|-|-|
|/pet/findByStatus|-|-|Finds Pets by status|-|
|/pet/{petId}|-|Updates a pet in the store with form data|Find pet by ID|Deletes a pet|
|/pet|-|-|-|-|
|/pet|-|-|-|-|

In [161]:
import pandas as pd
import requests
from http import HTTPStatus
from dataclasses import dataclass
from typing import Optional, List
from pprint import pprint

## API v3

In [74]:
DATA = 'https://petstore3.swagger.io/api/v3/openapi.json'
resp = requests.get(DATA)

if resp.status_code != HTTPStatus.OK:
    raise ConnectionError('Nie mogę pobrać danych')

data = resp.json()
api = pd.DataFrame(data['paths']).transpose()

def summary(x):
    if type(x) == dict:
        return x['summary']
    else:
        return pd.NA


api = api.applymap(summary)
api

,put,post,get,delete
/pet,Update an existing pet,Add a new pet to the store,<NA>,<NA>
/pet/findByStatus,<NA>,<NA>,Finds Pets by status,<NA>
/pet/findByTags,<NA>,<NA>,Finds Pets by tags,<NA>
/pet/{petId},<NA>,Updates a pet in the store with form data,Find pet by ID,Deletes a pet
/pet/{petId}/uploadImage,<NA>,uploads an image,<NA>,<NA>
/store/inventory,<NA>,<NA>,Returns pet inventories by status,<NA>
/store/order,<NA>,Place an order for a pet,<NA>,<NA>
/store/order/{orderId},<NA>,<NA>,Find purchase order by ID,Delete purchase order by ID
/user,<NA>,Create user,<NA>,<NA>
/user/createWithList,<NA>,Creates list of users with given input array,<NA>,<NA>
/user/login,<NA>,<NA>,Logs user into the system,<NA>
/user/logout,<NA>,<NA>,Logs out current logged in user session,<NA>
/user/{username},Update user,<NA>,Get user by user name,Delete user

## API v2

In [76]:
DATA = 'https://petstore.swagger.io/v2/swagger.json'

resp = requests.get(DATA)
resp.raise_for_status()

data = resp.json()
api = pd.DataFrame(data['paths']).transpose()
api = api.applymap(lambda x: x['summary'] if type(x) == dict else pd.NA)
api

,post,put,get,delete
/pet/{petId}/uploadImage,uploads an image,<NA>,<NA>,<NA>
/pet,Add a new pet to the store,Update an existing pet,<NA>,<NA>
/pet/findByStatus,<NA>,<NA>,Finds Pets by status,<NA>
/pet/findByTags,<NA>,<NA>,Finds Pets by tags,<NA>
/pet/{petId},Updates a pet in the store with form data,<NA>,Find pet by ID,Deletes a pet
/store/order,Place an order for a pet,<NA>,<NA>,<NA>
/store/order/{orderId},<NA>,<NA>,Find purchase order by ID,Delete purchase order by ID
/store/inventory,<NA>,<NA>,Returns pet inventories by status,<NA>
/user/createWithArray,Creates list of users with given input array,<NA>,<NA>,<NA>
/user/createWithList,Creates list of users with given input array,<NA>,<NA>,<NA>
/user/{username},<NA>,Updated user,Get user by user name,Delete user
/user/login,<NA>,<NA>,Logs user into the system,<NA>
/user/logout,<NA>,<NA>,Logs out current logged in user session,<NA>
/user,Create user,<NA>,<NA>,<NA>

## Forbidden

In [81]:
DATA = 'https://python.astrotech.io/_static/iris.json'
pd.read_json(DATA)

HTTPError: HTTP Error 403: Forbidden

In [83]:
resp = requests.get(DATA, headers={
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 11_0) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15',
})

In [86]:
pd.DataFrame(resp.json())

    sepalLength  sepalWidth  petalLength  petalWidth     species
0           5.1         3.5          1.4         0.2      setosa
1           4.9         3.0          1.4         0.2      setosa
2           4.7         3.2          1.3         0.2      setosa
3           4.6         3.1          1.5         0.2      setosa
4           5.0         3.6          1.4         0.2      setosa
5           5.4         3.9          1.7         0.4      setosa
6           4.6         3.4          1.4         0.3      setosa
7           5.0         3.4          1.5         0.2      setosa
8           4.4         2.9          1.4         0.2      setosa
9           4.9         3.1          1.5         0.1      setosa
10          7.0         3.2          4.7         1.4  versicolor
11          6.4         3.2          4.5         1.5  versicolor
12          6.9         3.1          4.9         1.5  versicolor
13          5.5         2.3          4.0         1.3  versicolor
14          6.5         2.8          4.6         1.5  versicolor
15          5.7         2.8          4.5         1.3  versicolor
16          6.3         3.3          4.7         1.6  versicolor
17          4.9         2.4          3.3         1.0  versicolor
18          6.6         2.9          4.6         1.3  versicolor
19          5.2         2.7          3.9         1.4  versicolor
20          6.3         3.3          6.0         2.5   virginica
21          5.8         2.7          5.1         1.9   virginica
22          7.1         3.0          5.9         2.1   virginica
23          6.3         2.9          5.6         1.8   virginica
24          6.5         3.0          5.8         2.2   virginica
25          7.6         3.0          6.6         2.1   virginica
26          4.9         2.5          4.5         1.7   virginica
27          7.3         2.9          6.3         1.8   virginica
28          6.7         2.5          5.8         1.8   virginica
29          7.2         3.6          6.1         2.5   virginica

In [87]:
pd.read_json?

In [88]:
data = [
    {"firstname": "Jan", "lastname": "Twardowski", "addresses": [
        {"street": "Kamienica Pod św. Janem Kapistranem", "city": "Kraków", "post_code": "31-008", "region": "Małopolskie", "country": "Poland"}]},

    {"firstname": "José", "lastname": "Jiménez", "addresses": [
        {"street": "2101 E NASA Pkwy", "city": "Houston", "post_code": 77058, "region": "Texas", "country": "USA"},
        {"street": "", "city": "Kennedy Space Center", "post_code": 32899, "region": "Florida", "country": "USA"}]},

    {"firstname": "Mark", "lastname": "Watney", "addresses": [
        {"street": "4800 Oak Grove Dr", "city": "Pasadena", "post_code": 91109, "region": "California", "country": "USA"},
        {"street": "2825 E Ave P", "city": "Palmdale", "post_code": 93550, "region": "California", "country": "USA"}]},

    {"firstname": "Иван", "lastname": "Иванович", "addresses": [
        {"street": "", "city": "Космодро́м Байкону́р", "post_code": "", "region": "Кызылординская область", "country": "Қазақстан"},
        {"street": "", "city": "Звёздный городо́к", "post_code": 141160, "region": "Московская область", "country": "Россия"}]},

    {"firstname": "Melissa", "lastname": "Lewis", "addresses": []},

    {"firstname": "Alex", "lastname": "Vogel", "addresses": [
        {"street": "Linder Hoehe", "city": "Köln", "post_code": 51147, "region": "North Rhine-Westphalia", "country": "Germany"}]}
]

In [89]:
pd.DataFrame(data)

  firstname   lastname                                          addresses
0        Jan  Twardowski  [{'street': 'Kamienica Pod św. Janem Kapistran...
1       José     Jiménez  [{'street': '2101 E NASA Pkwy', 'city': 'Houst...
2       Mark      Watney  [{'street': '4800 Oak Grove Dr', 'city': 'Pasa...
3       Иван    Иванович  [{'street': '', 'city': 'Космодро́м Байкону́р'...
4    Melissa       Lewis                                                 []
5       Alex       Vogel  [{'street': 'Linder Hoehe', 'city': 'Köln', 'p...

In [92]:
data = '[{"model":"authorization.user","pk":1,"fields":{"password":"pbkdf2_sha256$120000$gvEBNiCeTrYa0$5C+NiCeTrYsha1PHogqvXNiCeTrY0CRSLYYAA90=","last_login":"1970-01-01T00:00:00.000Z","is_superuser":false,"username":"commander","firstname":"Иван","lastname":"Иванович","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"eclss":["add","modify","view"]},{"communication":["add","modify","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":2,"fields":{"password":"pbkdf2_sha256$120000$eUNiCeTrYHoh$X32NiCeTrYZOWFdBcVT1l3NiCeTrY4WJVhr+cKg=","last_login":null,"is_superuser":false,"username":"executive-officer","firstname":"José","lastname":"Jiménez","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"eclss":["add","modify","view"]},{"communication":["add","modify","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":3,"fields":{"password":"pbkdf2_sha256$120000$3G0RNiCeTrYlaV1$mVb62WNiCeTrYQ9aYzTsSh74NiCeTrY2+c9/M=","last_login":"1970-01-01T00:00:00.000Z","is_superuser":false,"username":"crew-medical-officer","firstname":"Melissa","lastname":"Lewis","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":4,"fields":{"password":"pbkdf2_sha256$120000$QmSNiCeTrYBv$Nt1jhVyacNiCeTrYSuKzJ//WdyjlNiCeTrYYZ3sB1r0g=","last_login":null,"is_superuser":false,"username":"science-data-officer","firstname":"Mark","lastname":"Watney","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":5,"fields":{"password":"pbkdf2_sha256$120000$bxS4dNiCeTrY1n$Y8NiCeTrYRMa5bNJhTFjNiCeTrYp5swZni2RQbs=","last_login":null,"is_superuser":false,"username":"communication-officer","firstname":"Jan","lastname":"Twardowski","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":6,"fields":{"password":"pbkdf2_sha256$120000$aXNiCeTrY$UfCJrBh/qhXohNiCeTrYH8nsdANiCeTrYnShs9M/c=","last_login":null,"is_superuser":false,"username":"eclss-officer","firstname":"Harry","lastname":"Stamper","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"eclss":["add","modify","view"]},{"science":["add","modify","view"]}]}}]'

In [93]:
data

'[{"model":"authorization.user","pk":1,"fields":{"password":"pbkdf2_sha256$120000$gvEBNiCeTrYa0$5C+NiCeTrYsha1PHogqvXNiCeTrY0CRSLYYAA90=","last_login":"1970-01-01T00:00:00.000Z","is_superuser":false,"username":"commander","firstname":"Иван","lastname":"Иванович","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"eclss":["add","modify","view"]},{"communication":["add","modify","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":2,"fields":{"password":"pbkdf2_sha256$120000$eUNiCeTrYHoh$X32NiCeTrYZOWFdBcVT1l3NiCeTrY4WJVhr+cKg=","last_login":null,"is_superuser":false,"username":"executive-officer","firstname":"José","lastname":"Jiménez","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"eclss":["add","modify","view"]},{"communication":["add","modify","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":3,"fields":{"password":"pbkdf2_sha256$120000$3G0RNiCeTrYlaV1$mVb62WNiCeTrYQ9aYzTsSh74NiCeTrY2+c9/M=","last_login":"1970-01-01T00:00:00.000Z","is_superuser":false,"username":"crew-medical-officer","firstname":"Melissa","lastname":"Lewis","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":4,"fields":{"password":"pbkdf2_sha256$120000$QmSNiCeTrYBv$Nt1jhVyacNiCeTrYSuKzJ//WdyjlNiCeTrYYZ3sB1r0g=","last_login":null,"is_superuser":false,"username":"science-data-officer","firstname":"Mark","lastname":"Watney","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":5,"fields":{"password":"pbkdf2_sha256$120000$bxS4dNiCeTrY1n$Y8NiCeTrYRMa5bNJhTFjNiCeTrYp5swZni2RQbs=","last_login":null,"is_superuser":false,"username":"communication-officer","firstname":"Jan","lastname":"Twardowski","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":6,"fields":{"password":"pbkdf2_sha256$120000$aXNiCeTrY$UfCJrBh/qhXohNiCeTrYH8nsdANiCeTrYnShs9M/c=","last_login":null,"is_superuser":false,"username":"eclss-officer","firstname":"Harry","lastname":"Stamper","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"eclss":["add","modify","view"]},{"science":["add","modify","view"]}]}}]'

|firstname|lastname|is_staff|email|
|-|-|-|-|
|Jan|Twardowski|True|...|

In [113]:
DATA = '[{"model":"authorization.user","pk":1,"fields":{"password":"pbkdf2_sha256$120000$gvEBNiCeTrYa0$5C+NiCeTrYsha1PHogqvXNiCeTrY0CRSLYYAA90=","last_login":"1970-01-01T00:00:00.000Z","is_superuser":false,"username":"commander","firstname":"Иван","lastname":"Иванович","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"eclss":["add","modify","view"]},{"communication":["add","modify","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":2,"fields":{"password":"pbkdf2_sha256$120000$eUNiCeTrYHoh$X32NiCeTrYZOWFdBcVT1l3NiCeTrY4WJVhr+cKg=","last_login":null,"is_superuser":false,"username":"executive-officer","firstname":"José","lastname":"Jiménez","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"eclss":["add","modify","view"]},{"communication":["add","modify","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":3,"fields":{"password":"pbkdf2_sha256$120000$3G0RNiCeTrYlaV1$mVb62WNiCeTrYQ9aYzTsSh74NiCeTrY2+c9/M=","last_login":"1970-01-01T00:00:00.000Z","is_superuser":false,"username":"crew-medical-officer","firstname":"Melissa","lastname":"Lewis","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":4,"fields":{"password":"pbkdf2_sha256$120000$QmSNiCeTrYBv$Nt1jhVyacNiCeTrYSuKzJ//WdyjlNiCeTrYYZ3sB1r0g=","last_login":null,"is_superuser":false,"username":"science-data-officer","firstname":"Mark","lastname":"Watney","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":5,"fields":{"password":"pbkdf2_sha256$120000$bxS4dNiCeTrY1n$Y8NiCeTrYRMa5bNJhTFjNiCeTrYp5swZni2RQbs=","last_login":null,"is_superuser":false,"username":"communication-officer","firstname":"Jan","lastname":"Twardowski","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":6,"fields":{"password":"pbkdf2_sha256$120000$aXNiCeTrY$UfCJrBh/qhXohNiCeTrYH8nsdANiCeTrYnShs9M/c=","last_login":null,"is_superuser":false,"username":"eclss-officer","firstname":"Harry","lastname":"Stamper","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"eclss":["add","modify","view"]},{"science":["add","modify","view"]}]}}]'
DATA

'[{"model":"authorization.user","pk":1,"fields":{"password":"pbkdf2_sha256$120000$gvEBNiCeTrYa0$5C+NiCeTrYsha1PHogqvXNiCeTrY0CRSLYYAA90=","last_login":"1970-01-01T00:00:00.000Z","is_superuser":false,"username":"commander","firstname":"Иван","lastname":"Иванович","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"eclss":["add","modify","view"]},{"communication":["add","modify","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":2,"fields":{"password":"pbkdf2_sha256$120000$eUNiCeTrYHoh$X32NiCeTrYZOWFdBcVT1l3NiCeTrY4WJVhr+cKg=","last_login":null,"is_superuser":false,"username":"executive-officer","firstname":"José","lastname":"Jiménez","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"eclss":["add","modify","view"]},{"communication":["add","modify","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":3,"fields":{"password":"pbkdf2_sha256$120000$3G0RNiCeTrYlaV1$mVb62WNiCeTrYQ9aYzTsSh74NiCeTrY2+c9/M=","last_login":"1970-01-01T00:00:00.000Z","is_superuser":false,"username":"crew-medical-officer","firstname":"Melissa","lastname":"Lewis","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"medical":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":4,"fields":{"password":"pbkdf2_sha256$120000$QmSNiCeTrYBv$Nt1jhVyacNiCeTrYSuKzJ//WdyjlNiCeTrYYZ3sB1r0g=","last_login":null,"is_superuser":false,"username":"science-data-officer","firstname":"Mark","lastname":"Watney","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":5,"fields":{"password":"pbkdf2_sha256$120000$bxS4dNiCeTrY1n$Y8NiCeTrYRMa5bNJhTFjNiCeTrYp5swZni2RQbs=","last_login":null,"is_superuser":false,"username":"communication-officer","firstname":"Jan","lastname":"Twardowski","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","modify","view"]},{"science":["add","modify","view"]}]}},{"model":"authorization.user","pk":6,"fields":{"password":"pbkdf2_sha256$120000$aXNiCeTrY$UfCJrBh/qhXohNiCeTrYH8nsdANiCeTrYnShs9M/c=","last_login":null,"is_superuser":false,"username":"eclss-officer","firstname":"Harry","lastname":"Stamper","email":"","is_staff":true,"is_active":true,"date_joined":"1970-01-01T00:00:00.000Z","groups":[1],"user_permissions":[{"communication":["add","view"]},{"eclss":["add","modify","view"]},{"science":["add","modify","view"]}]}}]'

In [105]:
pd.read_json(DATA)

                model  pk                                             fields
0  authorization.user   1  {'password': 'pbkdf2_sha256$120000$gvEBNiCeTrY...
1  authorization.user   2  {'password': 'pbkdf2_sha256$120000$eUNiCeTrYHo...
2  authorization.user   3  {'password': 'pbkdf2_sha256$120000$3G0RNiCeTrY...
3  authorization.user   4  {'password': 'pbkdf2_sha256$120000$QmSNiCeTrYB...
4  authorization.user   5  {'password': 'pbkdf2_sha256$120000$bxS4dNiCeTr...
5  authorization.user   6  {'password': 'pbkdf2_sha256$120000$aXNiCeTrY$U...

In [114]:
import json

data = json.loads(DATA)
data = [x['fields'] for x in data]

pd.DataFrame(data)

,password,last_login,is_superuser,username,firstname,lastname,email,is_staff,is_active,date_joined,groups,user_permissions
0,pbkdf2_sha256$120000$gvEBNiCeTrYa0$5C+NiCeTrYs...,1970-01-01T00:00:00.000Z,False,commander,Иван,Иванович,,True,True,1970-01-01T00:00:00.000Z,[1],"[{'eclss': ['add', 'modify', 'view']}, {'commu..."
1,pbkdf2_sha256$120000$eUNiCeTrYHoh$X32NiCeTrYZO...,None,False,executive-officer,José,Jiménez,,True,True,1970-01-01T00:00:00.000Z,[1],"[{'eclss': ['add', 'modify', 'view']}, {'commu..."
2,pbkdf2_sha256$120000$3G0RNiCeTrYlaV1$mVb62WNiC...,1970-01-01T00:00:00.000Z,False,crew-medical-officer,Melissa,Lewis,,True,True,1970-01-01T00:00:00.000Z,[1],"[{'communication': ['add', 'view']}, {'medical..."
3,pbkdf2_sha256$120000$QmSNiCeTrYBv$Nt1jhVyacNiC...,None,False,science-data-officer,Mark,Watney,,True,True,1970-01-01T00:00:00.000Z,[1],"[{'communication': ['add', 'view']}, {'science..."
4,pbkdf2_sha256$120000$bxS4dNiCeTrY1n$Y8NiCeTrYR...,None,False,communication-officer,Jan,Twardowski,,True,True,1970-01-01T00:00:00.000Z,[1],"[{'communication': ['add', 'modify', 'view']},..."
5,pbkdf2_sha256$120000$aXNiCeTrY$UfCJrBh/qhXohNi...,None,False,eclss-officer,Harry,Stamper,,True,True,1970-01-01T00:00:00.000Z,[1],"[{'communication': ['add', 'view']}, {'eclss':..."

In [198]:
DATA = """[
    {"firstname": "Jan", "lastname": "Twardowski", "addresses": [
        {"street": "Kamienica Pod św. Janem Kapistranem", "city": "Kraków", "post_code": "31-008", "region": "Małopolskie", "country": "Poland"}]},

    {"firstname": "José", "lastname": "Jiménez", "addresses": [
        {"street": "2101 E NASA Pkwy", "city": "Houston", "post_code": 77058, "region": "Texas", "country": "USA"},
        {"street": "", "city": "Kennedy Space Center", "post_code": 32899, "region": "Florida", "country": "USA"}]},

    {"firstname": "Mark", "lastname": "Watney", "addresses": [
        {"street": "4800 Oak Grove Dr", "city": "Pasadena", "post_code": 91109, "region": "California", "country": "USA"},
        {"street": "2825 E Ave P", "city": "Palmdale", "post_code": 93550, "region": "California", "country": "USA"}]},

    {"firstname": "Иван", "lastname": "Иванович", "addresses": [
        {"street": "", "city": "Космодро́м Байкону́р", "post_code": "", "region": "Кызылординская область", "country": "Қазақстан"},
        {"street": "", "city": "Звёздный городо́к", "post_code": 141160, "region": "Московская область", "country": "Россия"}]},

    {"firstname": "Melissa", "lastname": "Lewis", "addresses": []},

    {"firstname": "Alex", "lastname": "Vogel", "addresses": [
        {"street": "Linder Hoehe", "city": "Köln", "post_code": 51147, "region": "North Rhine-Westphalia", "country": "Germany"}]}
]"""

In [199]:
@dataclass
class Address:
    user_id: id
    street: str
    city: str
    post_code: str
    region: str
    country: str


@dataclass
class User:
    uid: int
    firstname: str
    lastname: str
         
        
users = []
addresses = []

for i, row in enumerate(json.loads(DATA), start=1):
    for address in row.pop('addresses'):
        addr = Address(user_id=i, **address)
        addresses.append(addr)
        
    row['uid'] = i
    user = User(**row)
    users.append(user)
    
users = pd.DataFrame(users)
addresses = pd.DataFrame(addresses)

data = users.merge(addresses, left_on='uid', right_on='user_id')
data.drop(columns=['user_id'], inplace=True)

data

,uid,firstname,lastname,street,city,post_code,region,country
0,1,Jan,Twardowski,Kamienica Pod św. Janem Kapistranem,Kraków,31-008,Małopolskie,Poland
1,2,José,Jiménez,2101 E NASA Pkwy,Houston,77058,Texas,USA
2,2,José,Jiménez,,Kennedy Space Center,32899,Florida,USA
3,3,Mark,Watney,4800 Oak Grove Dr,Pasadena,91109,California,USA
4,3,Mark,Watney,2825 E Ave P,Palmdale,93550,California,USA
5,4,Иван,Иванович,,Космодро́м Байкону́р,,Кызылординская область,Қазақстан
6,4,Иван,Иванович,,Звёздный городо́к,141160,Московская область,Россия
7,6,Alex,Vogel,Linder Hoehe,Köln,51147,North Rhine-Westphalia,Germany